org: robertbuna
app: budget-app-app
# NOTE: update this with your service name
service: budget-app

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

  environment:
    tableName: Transactions
    tableBudgetName: Budgets
    tableLOName: Leftovers
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*" 

functions:
  manual_entry:
    handler: manual_entry.main
    events:
      - http:
          path: manual_entry
          method: post
          cors: true
          authorizer: aws_iam

  create_budget:
    handler: create_budget.main
    events:
      - http:
          path: create_budget
          method: post
          cors: true
          authorizer: aws_iam        

  monthly_transactions:
    handler: monthly_transactions.main
    events:
      - http:
          path: transactions/{id}
          method: get
          cors: true
          authorizer: aws_iam

  assign_budget:
    handler: assign_budget.main
    event:
      - http:
        path: assign_budget/{transactionId}
        method: put
        cors: true
        authorizer: aws_iam

  add_attachment:
    handler: add_attachment.main
    event:
      - http:
        path: add_attachment/{transactionId}
        method: put
        cors: true
        authorizer: aws_iam      

  delete_transaction:
    handler: delete_transaction.main
    events:
      - http:
        path: delete_transaction/{transactionId}
        method: delete
        cors: true
        authorizer: aws_iam  

  billing:
    handler: billing.main
    events:
      - http:
        path: billing
        method: post
        cors: true
        authorizer: aws_iam